kind: Secret
apiVersion: v1
metadata:
  name: simple-python-app-generic-webhook-secret
  namespace: sample-python-app
  selfLink: >-
    /api/v1/namespaces/sample-python-app/secrets/simple-python-app-generic-webhook-secret
  uid: 58023bc0-7419-11ea-abf6-02450387fbf4
  resourceVersion: '164990791'
  creationTimestamp: '2020-04-01T13:04:38Z'
data:
  WebHookSecretKey: ODg2ZTUzMjNjZWU5NTkxMw==
type: Opaque
